CREATE DATABASE EMPLEADOS;

USE EMPLEADOS;

CREATE TABLE USUARIO (
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	USAURIO VARCHAR(20),
	CLAVE VARCHAR(20)
)

GO
CREATE TABLE BITACORA (
	ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
	TIPO VARCHAR(20),
	FECHA DATETIME
)

GO
CREATE TABLE EMPLEADO (
	ID_EMPLEADO INT PRIMARY KEY,
	NOMBRE VARCHAR(20),
	DIRECCION VARCHAR(50)
)

GO
CREATE PROCEDURE PROCEDIMIENTO_INSERTAR_EMPLEADO
(
@ID_EMPLEADO INT,
@NOMBRE VARCHAR(20),
@DIRECCION VARCHAR(20)
)
AS
BEGIN
	INSERT INTO EMPLEADO
	(ID_EMPLEADO, NOMBRE, DIRECCION)
	VALUES
	(@ID_EMPLEADO, @NOMBRE, @DIRECCION)
END
go
exec PROCEDIMIENTO_INSERTAR_EMPLEADO 114230534, 'Marco', 'Acosta'

select * from EMPLEADO